### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by Arturacf**
Changed "requeriments" to "requirements"

### CODE REVIEW

**Comment by vsoch** [comment]
How do you know the file isn't called that?

**Comment by vsoch** [comment]
The "mistake" is done in three places, so I'm wondering if it's supposed to be like that. Maybe you can find the original repo?

**Comment by Arturacf** [comment]
You're right, thanks

**Comment by vsoch** [comment]
Thanks anyway @Arturacf - appreciated! Just to note, this repository is more of a dataset (Dockerfiles of the past for analysis) over a repository of Dockerfiles that should be optimized for build, etc.

**Pull request closed without merging**
